=== speck14/animal-shelter-schema/extended-schema/extended-schema-single-file.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "file:///C:\\Users\\shannon.peck\\Documents\\JSON-practice\\JSON_schema_project\\animal-shelter-schema\\extended-schema\\extended_schema.json",
  "title": "Animal Shelter JSON",
  "description": "Animal in an animal shelter",
  "type": "object",
  "properties": {
      "petID": {
          "description": "The unique identifier for the pet",
          "type": "integer"
      },
      "petName": {
          "description": "Name of pet",
          "type": "string"
      },
      "animalDescription": {
          "description": "description of pet",
          "$ref": "#/animalDescription"
      },
      "dateOfBirth": {
      "description": "Approximate date of birth",  
      "$ref": "#/date"
      },
      "intakeDate": {
          "description": "Date pet was taken into shelter",
          "$ref": "#/date"
      },
      "numIntakes": {
          "description": "Number of times animal has been in shelter, including current intake",
          "type": "integer",
          "minimum": 1
      }
  },
    "animalDescription": {
    "description": "Description of animal",
    "type": "object",
    "properties": {
      "species": {
        "description": "Species of animal",
        "type": "string",
        "enum": ["Feline", "Canine"]
        },
        "breed": {
          "description": "Breed(s) of pet",
          "type": "array",
          "items": {
              "type": "string"
          },
          "$ref": "#/itemReqs"
        },
        "markings": {
          "description": "Coloration and markings of pet",
          "type": "array",
          "items": {
              "type": "string"
          },
          "$ref": "#/itemReqs"
        }
    },
    "required": [ "species", "breed", "markings"]
  },
    "date": {
      "type": "string",
  "format": "date"
    },
    "itemReqs": {
      "minItems": 1,
      "uniqueItems": true
    },
  "required": ["petID", "petName", "animalDescription", "intakeDate", "numIntakes"]
}

=== speck14/animal-shelter-schema/extended-schema/examples.json
[
  {
    "petID": 1,
    "petName": "Emma",
    "animalDescription":  {
      "species": "Canine",
      "breed": ["bulldog"],
      "markings": ["black", "white chest patch"]
    },
    "dateOfBirth": "2008-10-25",
    "intakeDate": "2011-10-25",
    "numIntakes": 1
  },  
  {
    "petID": 2,
    "petName": "Charles",
    "animalDescription": {
      "species": "Canine",
      "breed": ["pit bull", "boxer", "chihuahua"],
      "markings": ["brown", "white"]
    },
    "intakeDate": "2014-04-13",
    "numIntakes": 3
  },  
  {
    "petID": 3,
    "petName": "Dennis",
    "animalDescription": {
      "species": "Feline",
      "breed": ["DSH"],
      "markings": ["orange", "tabby"]
    },
    "dateOfBirth": "2020-04-24",
    "intakeDate": "2020-05-25",
    "numIntakes": 2
  },  
  {
    "petID": 4,
    "petName": "Nissa",
    "animalDescription": {
      "species": "Feline",
      "breed": ["DLH"],
      "markings": ["black", "white", "tuxedo"]
    },
    "intakeDate": "2018-06-01",
    "numIntakes": 2
  }
]
